// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppBadgeService keeps the launcher/taskbar badge in sync with the unread
 * state shown by the application. The platform implementation is supplied by
 * Wails3 (macOS Dock and Windows taskbar; Linux is a safe no-op).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function SetCount(count: number): $CancellablePromise<void> {
    return $Call.ByID(586170112, count);
}
