// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as chat$0 from "../chat/models.js";

export function AcceptAttachment(attachmentID: string): $CancellablePromise<chat$0.Attachment> {
    return $Call.ByID(1876449890, attachmentID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AcceptFriendRequest(requestID: string): $CancellablePromise<void> {
    return $Call.ByID(2475943332, requestID);
}

export function CancelAttachment(attachmentID: string): $CancellablePromise<void> {
    return $Call.ByID(3051208600, attachmentID);
}

export function ClearApplicationData(): $CancellablePromise<void> {
    return $Call.ByID(3831967442);
}

export function ClearConversation(deviceID: string): $CancellablePromise<chat$0.ClearConversationResult> {
    return $Call.ByID(676496123, deviceID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DefaultAttachmentPath(): $CancellablePromise<string> {
    return $Call.ByID(1346070090);
}

export function DeleteMessage(messageID: string): $CancellablePromise<void> {
    return $Call.ByID(1954844807, messageID);
}

export function EnsureConversation(deviceID: string): $CancellablePromise<string> {
    return $Call.ByID(319214306, deviceID);
}

export function GetAppVersion(): $CancellablePromise<string> {
    return $Call.ByID(484320968);
}

export function GetAttachmentDetails(attachmentID: string): $CancellablePromise<chat$0.AttachmentDetails> {
    return $Call.ByID(3275170694, attachmentID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetAttachmentPreview(attachmentID: string): $CancellablePromise<string> {
    return $Call.ByID(778582068, attachmentID);
}

export function GetDeviceInfo(): $CancellablePromise<chat$0.DeviceInfo> {
    return $Call.ByID(266453439).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetProfile(): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(633746438).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ListConversations(): $CancellablePromise<chat$0.Conversation[]> {
    return $Call.ByID(225306197).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListFriendRequests(): $CancellablePromise<chat$0.FriendRequest[]> {
    return $Call.ByID(4045668969).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ListFriends(): $CancellablePromise<chat$0.Peer[]> {
    return $Call.ByID(3341120740).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ListMessages(conversationID: string): $CancellablePromise<chat$0.Message[]> {
    return $Call.ByID(2803775171, conversationID).then(($result: any) => {
        return $$createType12($result);
    });
}

export function ListPeers(): $CancellablePromise<chat$0.Peer[]> {
    return $Call.ByID(1603588904).then(($result: any) => {
        return $$createType10($result);
    });
}

export function MarkConversationRead(deviceID: string): $CancellablePromise<void> {
    return $Call.ByID(997042317, deviceID);
}

export function MigrateAttachmentStorage(targetRoot: string): $CancellablePromise<chat$0.AttachmentMigrationResult> {
    return $Call.ByID(3167525510, targetRoot).then(($result: any) => {
        return $$createType13($result);
    });
}

export function NetworkStatus(): $CancellablePromise<chat$0.NetworkStatus> {
    return $Call.ByID(175001069).then(($result: any) => {
        return $$createType14($result);
    });
}

export function OpenAttachment(attachmentID: string): $CancellablePromise<void> {
    return $Call.ByID(2633859322, attachmentID);
}

export function PickDirectory(): $CancellablePromise<string> {
    return $Call.ByID(875816205);
}

export function PickFile(): $CancellablePromise<string> {
    return $Call.ByID(2768914208);
}

export function RejectAttachment(attachmentID: string): $CancellablePromise<void> {
    return $Call.ByID(2407074389, attachmentID);
}

export function RejectFriendRequest(requestID: string): $CancellablePromise<void> {
    return $Call.ByID(143154017, requestID);
}

export function ResetAvatar(): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(3245822307).then(($result: any) => {
        return $$createType4($result);
    });
}

export function RetryAttachment(messageID: string): $CancellablePromise<chat$0.Message> {
    return $Call.ByID(2148764198, messageID).then(($result: any) => {
        return $$createType11($result);
    });
}

export function RetryMessage(messageID: string): $CancellablePromise<chat$0.Message> {
    return $Call.ByID(2933069522, messageID).then(($result: any) => {
        return $$createType11($result);
    });
}

export function RevealAttachment(attachmentID: string): $CancellablePromise<void> {
    return $Call.ByID(2289429539, attachmentID);
}

export function RunNetworkDiagnostic(): $CancellablePromise<chat$0.DiagnosticResult> {
    return $Call.ByID(3959132677).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * SaveAttachmentAs lets a user choose the final path for a pending attachment.
 * The temporary download is moved only after the user confirms the destination.
 */
export function SaveAttachmentAs(attachmentID: string): $CancellablePromise<chat$0.Attachment> {
    return $Call.ByID(2973575367, attachmentID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SaveAttachmentCopy(attachmentID: string): $CancellablePromise<void> {
    return $Call.ByID(3210620898, attachmentID);
}

export function ScanPeers(): $CancellablePromise<void> {
    return $Call.ByID(786209235);
}

export function SendFile(deviceID: string, path: string): $CancellablePromise<chat$0.Message> {
    return $Call.ByID(184536515, deviceID, path).then(($result: any) => {
        return $$createType11($result);
    });
}

export function SendFriendRequest(deviceID: string, message: string): $CancellablePromise<chat$0.FriendRequest> {
    return $Call.ByID(3674668394, deviceID, message).then(($result: any) => {
        return $$createType7($result);
    });
}

export function SendImage(deviceID: string, dataURL: string): $CancellablePromise<chat$0.Message> {
    return $Call.ByID(1964687738, deviceID, dataURL).then(($result: any) => {
        return $$createType11($result);
    });
}

export function SendMessage(deviceID: string, content: string): $CancellablePromise<chat$0.Message> {
    return $Call.ByID(3289858148, deviceID, content).then(($result: any) => {
        return $$createType11($result);
    });
}

export function SendMessageWithMetadata(deviceID: string, content: string, quoteMessageID: string, quoteContent: string, forwardedFrom: string): $CancellablePromise<chat$0.Message> {
    return $Call.ByID(1947523705, deviceID, content, quoteMessageID, quoteContent, forwardedFrom).then(($result: any) => {
        return $$createType11($result);
    });
}

export function SetAutoSave(value: boolean): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(865606631, value).then(($result: any) => {
        return $$createType4($result);
    });
}

export function SetAvatar(sourcePath: string): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(1280700672, sourcePath).then(($result: any) => {
        return $$createType4($result);
    });
}

export function SetDiscoverable(value: boolean): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(4207746782, value).then(($result: any) => {
        return $$createType4($result);
    });
}

export function SetFileSavePath(path: string): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(3137600833, path).then(($result: any) => {
        return $$createType4($result);
    });
}

export function SetLaunchAtStartup(value: boolean): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(3105969280, value).then(($result: any) => {
        return $$createType4($result);
    });
}

export function SetMessageFavorite(messageID: string, favorite: boolean): $CancellablePromise<void> {
    return $Call.ByID(2693562804, messageID, favorite);
}

export function SetPeerRemark(deviceID: string, remark: string): $CancellablePromise<void> {
    return $Call.ByID(22082657, deviceID, remark);
}

export function SetTheme(theme: string): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(3854263238, theme).then(($result: any) => {
        return $$createType4($result);
    });
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(2735166081);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(2833071355);
}

export function UpdateProfile(profile: chat$0.Profile): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(1127029007, profile).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = chat$0.Attachment.createFrom;
const $$createType1 = chat$0.ClearConversationResult.createFrom;
const $$createType2 = chat$0.AttachmentDetails.createFrom;
const $$createType3 = chat$0.DeviceInfo.createFrom;
const $$createType4 = chat$0.Profile.createFrom;
const $$createType5 = chat$0.Conversation.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = chat$0.FriendRequest.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = chat$0.Peer.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = chat$0.Message.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = chat$0.AttachmentMigrationResult.createFrom;
const $$createType14 = chat$0.NetworkStatus.createFrom;
const $$createType15 = chat$0.DiagnosticResult.createFrom;
