// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as chat$0 from "../chat/models.js";

export function AcceptAttachment(attachmentID: string): $CancellablePromise<chat$0.Attachment> {
    return $Call.ByID(1876449890, attachmentID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AcceptFriendRequest(requestID: string): $CancellablePromise<void> {
    return $Call.ByID(2475943332, requestID);
}

export function CancelAttachment(attachmentID: string): $CancellablePromise<void> {
    return $Call.ByID(3051208600, attachmentID);
}

export function CancelSharedTransfer(transferID: string): $CancellablePromise<void> {
    return $Call.ByID(3829352919, transferID);
}

export function ClearApplicationData(): $CancellablePromise<void> {
    return $Call.ByID(3831967442);
}

export function ClearConversation(deviceID: string): $CancellablePromise<chat$0.ClearConversationResult> {
    return $Call.ByID(676496123, deviceID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ClearFriendRequestHistory(): $CancellablePromise<void> {
    return $Call.ByID(1437948343);
}

export function CopySharedEntry(relativePath: string, targetDirectory: string): $CancellablePromise<void> {
    return $Call.ByID(3244755481, relativePath, targetDirectory);
}

export function CreateSharedFolder(relativePath: string, name: string): $CancellablePromise<chat$0.SharedEntry> {
    return $Call.ByID(1191979458, relativePath, name).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DefaultAttachmentPath(): $CancellablePromise<string> {
    return $Call.ByID(1346070090);
}

export function DeleteMessage(messageID: string): $CancellablePromise<void> {
    return $Call.ByID(1954844807, messageID);
}

export function DeleteSharedEntry(relativePath: string): $CancellablePromise<void> {
    return $Call.ByID(76158059, relativePath);
}

export function DisableSharedFolder(): $CancellablePromise<void> {
    return $Call.ByID(2991895760);
}

export function DownloadFriendSharedEntry(deviceID: string, relativePath: string): $CancellablePromise<chat$0.SharedTransfer> {
    return $Call.ByID(2893260122, deviceID, relativePath).then(($result: any) => {
        return $$createType3($result);
    });
}

export function EnsureConversation(deviceID: string): $CancellablePromise<string> {
    return $Call.ByID(319214306, deviceID);
}

export function GetAppVersion(): $CancellablePromise<string> {
    return $Call.ByID(484320968);
}

export function GetAttachmentDetails(attachmentID: string): $CancellablePromise<chat$0.AttachmentDetails> {
    return $Call.ByID(3275170694, attachmentID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetAttachmentImage(attachmentID: string): $CancellablePromise<string> {
    return $Call.ByID(3813136653, attachmentID);
}

export function GetAttachmentPreview(attachmentID: string): $CancellablePromise<string> {
    return $Call.ByID(778582068, attachmentID);
}

/**
 * GetAttachmentThumbnail is intentionally separate from GetAttachmentImage.
 * Chat bubbles should never load a large local original just to render a
 * preview, while the image viewer must use the original when it is available.
 */
export function GetAttachmentThumbnail(attachmentID: string): $CancellablePromise<string> {
    return $Call.ByID(857806412, attachmentID);
}

export function GetDeviceInfo(): $CancellablePromise<chat$0.DeviceInfo> {
    return $Call.ByID(266453439).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetFriendSharedEntryDetails(deviceID: string, relativePath: string): $CancellablePromise<chat$0.SharedEntry> {
    return $Call.ByID(490667166, deviceID, relativePath).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetFriendSharedEntryPreview(deviceID: string, relativePath: string): $CancellablePromise<string> {
    return $Call.ByID(1887022076, deviceID, relativePath);
}

export function GetFriendSharedEntryThumbnail(deviceID: string, relativePath: string): $CancellablePromise<string> {
    return $Call.ByID(3581863860, deviceID, relativePath);
}

/**
 * GetFriendSharedEntryThumbnailCached serves the desktop-side cached preview
 * when the shared-drive list has already fetched it.  A cache miss is still a
 * single bounded request; the Android side may return an empty payload while
 * generating the thumbnail, so the viewer never waits for generation.
 */
export function GetFriendSharedEntryThumbnailCached(deviceID: string, relativePath: string, entryID: string, fileSize: number, modifiedAt: string): $CancellablePromise<string> {
    return $Call.ByID(3610340958, deviceID, relativePath, entryID, fileSize, modifiedAt);
}

export function GetFriendSharedEntryThumbnails(deviceID: string, requests: chat$0.SharedThumbnailRequest[]): $CancellablePromise<chat$0.SharedThumbnailResult[]> {
    return $Call.ByID(3720797765, deviceID, requests).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetMessage bootstraps the selected image before the viewer loads the full
 * conversation history for previous/next navigation.
 */
export function GetMessage(messageID: string): $CancellablePromise<chat$0.Message> {
    return $Call.ByID(3688160572, messageID).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetMyQRCode creates the local, offline friend-card QR code. It contains
 * discoverable identity metadata only; the full DeviceID remains the value
 * used by the authenticated protocol. Returning a data URL keeps the card
 * usable while the application is offline and avoids an external QR service.
 */
export function GetMyQRCode(): $CancellablePromise<string> {
    return $Call.ByID(1439315809);
}

export function GetProfile(): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(633746438).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetSharedEntryDetails(relativePath: string): $CancellablePromise<chat$0.SharedEntry> {
    return $Call.ByID(3749520102, relativePath).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetSharedEntryPreview(relativePath: string): $CancellablePromise<string> {
    return $Call.ByID(4183612052, relativePath);
}

/**
 * GetSharedEntryThumbnail returns a small image-only preview for the shared
 * grid. The original file is intentionally not read into the webview.
 */
export function GetSharedEntryThumbnail(relativePath: string): $CancellablePromise<string> {
    return $Call.ByID(2944873388, relativePath);
}

export function GetSharedFolderSettings(): $CancellablePromise<chat$0.SharedFolderStatus> {
    return $Call.ByID(2793273685).then(($result: any) => {
        return $$createType10($result);
    });
}

export function HideFriendAndClearLocalData(deviceID: string): $CancellablePromise<void> {
    return $Call.ByID(2603092040, deviceID);
}

export function ImportSharedFiles(relativePath: string): $CancellablePromise<chat$0.SharedEntry[]> {
    return $Call.ByID(2212335558, relativePath).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ImportSharedFolder(relativePath: string): $CancellablePromise<chat$0.SharedEntry[]> {
    return $Call.ByID(2740777515, relativePath).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ListConversations(): $CancellablePromise<chat$0.Conversation[]> {
    return $Call.ByID(225306197).then(($result: any) => {
        return $$createType13($result);
    });
}

export function ListFriendRequests(): $CancellablePromise<chat$0.FriendRequest[]> {
    return $Call.ByID(4045668969).then(($result: any) => {
        return $$createType15($result);
    });
}

export function ListFriendSharedEntries(deviceID: string, relativePath: string): $CancellablePromise<chat$0.SharedEntry[]> {
    return $Call.ByID(2894093430, deviceID, relativePath).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ListFriendSharedEntriesPage(deviceID: string, relativePath: string, offset: number, limit: number): $CancellablePromise<chat$0.SharedEntriesPage> {
    return $Call.ByID(3330820637, deviceID, relativePath, offset, limit).then(($result: any) => {
        return $$createType16($result);
    });
}

export function ListFriends(): $CancellablePromise<chat$0.Peer[]> {
    return $Call.ByID(3341120740).then(($result: any) => {
        return $$createType18($result);
    });
}

export function ListMessages(conversationID: string): $CancellablePromise<chat$0.Message[]> {
    return $Call.ByID(2803775171, conversationID).then(($result: any) => {
        return $$createType19($result);
    });
}

export function ListPeers(): $CancellablePromise<chat$0.Peer[]> {
    return $Call.ByID(1603588904).then(($result: any) => {
        return $$createType18($result);
    });
}

export function ListSharedEntries(relativePath: string): $CancellablePromise<chat$0.SharedEntry[]> {
    return $Call.ByID(772166362, relativePath).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ListSharedEntriesPage(relativePath: string, offset: number, limit: number): $CancellablePromise<chat$0.SharedEntriesPage> {
    return $Call.ByID(3021393633, relativePath, offset, limit).then(($result: any) => {
        return $$createType16($result);
    });
}

export function MarkConversationRead(deviceID: string): $CancellablePromise<void> {
    return $Call.ByID(997042317, deviceID);
}

export function MarkConversationUnread(deviceID: string): $CancellablePromise<void> {
    return $Call.ByID(2857409466, deviceID);
}

export function MigrateAttachmentStorage(targetRoot: string): $CancellablePromise<chat$0.AttachmentMigrationResult> {
    return $Call.ByID(3167525510, targetRoot).then(($result: any) => {
        return $$createType20($result);
    });
}

export function MoveSharedEntry(relativePath: string, targetDirectory: string): $CancellablePromise<void> {
    return $Call.ByID(757497977, relativePath, targetDirectory);
}

export function NetworkStatus(): $CancellablePromise<chat$0.NetworkStatus> {
    return $Call.ByID(175001069).then(($result: any) => {
        return $$createType21($result);
    });
}

export function OpenAttachment(attachmentID: string): $CancellablePromise<void> {
    return $Call.ByID(2633859322, attachmentID);
}

export function OpenSharedDownload(targetPath: string): $CancellablePromise<void> {
    return $Call.ByID(1704113918, targetPath);
}

export function OpenSharedEntry(relativePath: string): $CancellablePromise<void> {
    return $Call.ByID(3246281806, relativePath);
}

export function PauseSharedTransfer(transferID: string): $CancellablePromise<void> {
    return $Call.ByID(3454468329, transferID);
}

export function PickDirectory(): $CancellablePromise<string> {
    return $Call.ByID(875816205);
}

export function PickFile(): $CancellablePromise<string> {
    return $Call.ByID(2768914208);
}

/**
 * PickFiles opens the native file picker in multi-selection mode. Keep the
 * single-file PickFile method for avatar and other existing callers.
 */
export function PickFiles(): $CancellablePromise<string[]> {
    return $Call.ByID(573458345).then(($result: any) => {
        return $$createType22($result);
    });
}

export function PickSharedDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1091777130);
}

/**
 * RefreshPeerAvatar is an explicit, on-demand avatar read. The engine only
 * invokes it from a user-facing chat/profile open, so background discovery and
 * ordinary message traffic never pull avatar bytes.
 */
export function RefreshPeerAvatar(deviceID: string): $CancellablePromise<void> {
    return $Call.ByID(84600919, deviceID);
}

/**
 * RefreshSharedStats explicitly recomputes the local shared-drive statistics.
 * Settings that change the counting scope, such as hidden-file visibility,
 * use this instead of waiting for the normal cached result.
 */
export function RefreshSharedStats(force: boolean): $CancellablePromise<chat$0.SharedFolderStatus> {
    return $Call.ByID(3196224838, force).then(($result: any) => {
        return $$createType10($result);
    });
}

export function RejectAttachment(attachmentID: string): $CancellablePromise<void> {
    return $Call.ByID(2407074389, attachmentID);
}

export function RejectFriendRequest(requestID: string): $CancellablePromise<void> {
    return $Call.ByID(143154017, requestID);
}

export function RemoveFriendAndClearLocalData(deviceID: string): $CancellablePromise<void> {
    return $Call.ByID(419947236, deviceID);
}

export function RenameSharedEntry(relativePath: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(2432293180, relativePath, newName);
}

export function ResetAvatar(): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(3245822307).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * RestoreHiddenFriend makes an explicitly opened contact visible in the main
 * friends list again. It does not change the friendship relationship.
 */
export function RestoreHiddenFriend(deviceID: string): $CancellablePromise<void> {
    return $Call.ByID(1472608839, deviceID);
}

export function ResumeSharedTransfer(transferID: string): $CancellablePromise<chat$0.SharedTransfer> {
    return $Call.ByID(2346923958, transferID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function RetryAttachment(messageID: string): $CancellablePromise<chat$0.Message> {
    return $Call.ByID(2148764198, messageID).then(($result: any) => {
        return $$createType8($result);
    });
}

export function RetryMessage(messageID: string): $CancellablePromise<chat$0.Message> {
    return $Call.ByID(2933069522, messageID).then(($result: any) => {
        return $$createType8($result);
    });
}

export function RevealAttachment(attachmentID: string): $CancellablePromise<void> {
    return $Call.ByID(2289429539, attachmentID);
}

export function RevealSharedDownload(targetPath: string): $CancellablePromise<void> {
    return $Call.ByID(576115583, targetPath);
}

export function RevealSharedEntry(relativePath: string): $CancellablePromise<void> {
    return $Call.ByID(1977560981, relativePath);
}

export function RunNetworkDiagnostic(): $CancellablePromise<chat$0.DiagnosticResult> {
    return $Call.ByID(3959132677).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * SaveAttachmentAs lets a user choose the final path for a pending attachment.
 * The temporary download is moved only after the user confirms the destination.
 */
export function SaveAttachmentAs(attachmentID: string): $CancellablePromise<chat$0.Attachment> {
    return $Call.ByID(2973575367, attachmentID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SaveAttachmentCopy(attachmentID: string): $CancellablePromise<void> {
    return $Call.ByID(3210620898, attachmentID);
}

export function SaveFriendSharedEntryAs(deviceID: string, relativePath: string): $CancellablePromise<chat$0.SharedTransfer> {
    return $Call.ByID(1564344737, deviceID, relativePath).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ScanPeers(): $CancellablePromise<void> {
    return $Call.ByID(786209235);
}

export function SendFile(deviceID: string, path: string): $CancellablePromise<chat$0.Message> {
    return $Call.ByID(184536515, deviceID, path).then(($result: any) => {
        return $$createType8($result);
    });
}

export function SendFriendRequest(deviceID: string, message: string): $CancellablePromise<chat$0.FriendRequest> {
    return $Call.ByID(3674668394, deviceID, message).then(($result: any) => {
        return $$createType14($result);
    });
}

export function SendImage(deviceID: string, dataURL: string): $CancellablePromise<chat$0.Message> {
    return $Call.ByID(1964687738, deviceID, dataURL).then(($result: any) => {
        return $$createType8($result);
    });
}

export function SendMessage(deviceID: string, content: string): $CancellablePromise<chat$0.Message> {
    return $Call.ByID(3289858148, deviceID, content).then(($result: any) => {
        return $$createType8($result);
    });
}

export function SendMessageWithMetadata(deviceID: string, content: string, quoteMessageID: string, quoteContent: string, forwardedFrom: string): $CancellablePromise<chat$0.Message> {
    return $Call.ByID(1947523705, deviceID, content, quoteMessageID, quoteContent, forwardedFrom).then(($result: any) => {
        return $$createType8($result);
    });
}

export function SetAutoSave(value: boolean): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(865606631, value).then(($result: any) => {
        return $$createType9($result);
    });
}

export function SetAvatar(sourcePath: string): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(1280700672, sourcePath).then(($result: any) => {
        return $$createType9($result);
    });
}

export function SetConversationPinned(deviceID: string, pinned: boolean): $CancellablePromise<void> {
    return $Call.ByID(1378522980, deviceID, pinned);
}

export function SetDiscoverable(value: boolean): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(4207746782, value).then(($result: any) => {
        return $$createType9($result);
    });
}

export function SetFileSavePath(path: string): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(3137600833, path).then(($result: any) => {
        return $$createType9($result);
    });
}

export function SetLaunchAtStartup(value: boolean): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(3105969280, value).then(($result: any) => {
        return $$createType9($result);
    });
}

export function SetMessageFavorite(messageID: string, favorite: boolean): $CancellablePromise<void> {
    return $Call.ByID(2693562804, messageID, favorite);
}

export function SetPeerRemark(deviceID: string, remark: string): $CancellablePromise<void> {
    return $Call.ByID(22082657, deviceID, remark);
}

export function SetSharedEnabled(enabled: boolean): $CancellablePromise<chat$0.SharedFolderStatus> {
    return $Call.ByID(3617952977, enabled).then(($result: any) => {
        return $$createType10($result);
    });
}

export function SetSharedFolder(path: string, enabled: boolean): $CancellablePromise<chat$0.SharedFolderStatus> {
    return $Call.ByID(593339220, path, enabled).then(($result: any) => {
        return $$createType10($result);
    });
}

export function SetTheme(theme: string): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(3854263238, theme).then(($result: any) => {
        return $$createType9($result);
    });
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(2735166081);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(2833071355);
}

export function UpdateProfile(profile: chat$0.Profile): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(1127029007, profile).then(($result: any) => {
        return $$createType9($result);
    });
}

// Private type creation functions
const $$createType0 = chat$0.Attachment.createFrom;
const $$createType1 = chat$0.ClearConversationResult.createFrom;
const $$createType2 = chat$0.SharedEntry.createFrom;
const $$createType3 = chat$0.SharedTransfer.createFrom;
const $$createType4 = chat$0.AttachmentDetails.createFrom;
const $$createType5 = chat$0.DeviceInfo.createFrom;
const $$createType6 = chat$0.SharedThumbnailResult.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = chat$0.Message.createFrom;
const $$createType9 = chat$0.Profile.createFrom;
const $$createType10 = chat$0.SharedFolderStatus.createFrom;
const $$createType11 = $Create.Array($$createType2);
const $$createType12 = chat$0.Conversation.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = chat$0.FriendRequest.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = chat$0.SharedEntriesPage.createFrom;
const $$createType17 = chat$0.Peer.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = $Create.Array($$createType8);
const $$createType20 = chat$0.AttachmentMigrationResult.createFrom;
const $$createType21 = chat$0.NetworkStatus.createFrom;
const $$createType22 = $Create.Array($Create.Any);
const $$createType23 = chat$0.DiagnosticResult.createFrom;
