// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ImageViewerService owns the optional native image viewer window. The main
 * chat window only passes database identifiers; the viewer reads the image
 * through the existing bound services after it has loaded.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function OpenImageViewer(conversationID: string, messageID: string): $CancellablePromise<void> {
    return $Call.ByID(433471697, conversationID, messageID);
}
