// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PreviewStreamService exposes short-lived, identifier-bound media URLs. The
 * browser can consume these URLs as normal HTTP streams, avoiding a large
 * base64 string and allowing a preview to begin as soon as the first bytes
 * arrive.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function CreateAttachmentPreviewURL(attachmentID: string): $CancellablePromise<string> {
    return $Call.ByID(1765016145, attachmentID);
}

export function CreateSharedPreviewURL(source: string, deviceID: string, relativePath: string): $CancellablePromise<string> {
    return $Call.ByID(36573581, source, deviceID, relativePath);
}
