// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SharedDriveWindowService owns the non-modal shared-drive window. The file
 * APIs remain on ChatService so the window can use the same authenticated
 * store and event stream as the main chat window.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function OpenFriendSharedDrive(deviceID: string): $CancellablePromise<void> {
    return $Call.ByID(735297941, deviceID);
}

export function OpenSharedDrive(): $CancellablePromise<void> {
    return $Call.ByID(2849001273);
}
