// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as chat$0 from "../chat/models.js";

export function AcceptAttachment(attachmentID: string): $CancellablePromise<chat$0.Attachment> {
    return $Call.ByID(2675195036, attachmentID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AcceptFriendRequest(requestID: string): $CancellablePromise<void> {
    return $Call.ByID(626977366, requestID);
}

export function ClearApplicationData(): $CancellablePromise<void> {
    return $Call.ByID(2436070024);
}

export function DefaultAttachmentPath(): $CancellablePromise<string> {
    return $Call.ByID(3559281932);
}

export function EnsureConversation(deviceID: string): $CancellablePromise<string> {
    return $Call.ByID(2675557384, deviceID);
}

export function GetAppVersion(): $CancellablePromise<string> {
    return $Call.ByID(1139715598);
}

export function GetAttachmentPreview(attachmentID: string): $CancellablePromise<string> {
    return $Call.ByID(1049877774, attachmentID);
}

export function GetDeviceInfo(): $CancellablePromise<chat$0.DeviceInfo> {
    return $Call.ByID(4163355485).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetProfile(): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(84695576).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListConversations(): $CancellablePromise<chat$0.Conversation[]> {
    return $Call.ByID(2822523595).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ListFriendRequests(): $CancellablePromise<chat$0.FriendRequest[]> {
    return $Call.ByID(4158195863).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListFriends(): $CancellablePromise<chat$0.Peer[]> {
    return $Call.ByID(1157847646).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ListMessages(conversationID: string): $CancellablePromise<chat$0.Message[]> {
    return $Call.ByID(4083532673, conversationID).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ListPeers(): $CancellablePromise<chat$0.Peer[]> {
    return $Call.ByID(39298642).then(($result: any) => {
        return $$createType8($result);
    });
}

export function MarkConversationRead(deviceID: string): $CancellablePromise<void> {
    return $Call.ByID(2055042427, deviceID);
}

export function MigrateAttachmentStorage(targetRoot: string): $CancellablePromise<chat$0.AttachmentMigrationResult> {
    return $Call.ByID(4061785384, targetRoot).then(($result: any) => {
        return $$createType11($result);
    });
}

export function NetworkStatus(): $CancellablePromise<chat$0.NetworkStatus> {
    return $Call.ByID(2081196511).then(($result: any) => {
        return $$createType12($result);
    });
}

export function PickDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1110197963);
}

export function PickFile(): $CancellablePromise<string> {
    return $Call.ByID(953961278);
}

export function RejectAttachment(attachmentID: string): $CancellablePromise<void> {
    return $Call.ByID(766550483, attachmentID);
}

export function RejectFriendRequest(requestID: string): $CancellablePromise<void> {
    return $Call.ByID(1431884687, requestID);
}

export function ResetAvatar(): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(3067976201).then(($result: any) => {
        return $$createType2($result);
    });
}

export function RunNetworkDiagnostic(): $CancellablePromise<chat$0.DiagnosticResult> {
    return $Call.ByID(3205563623).then(($result: any) => {
        return $$createType13($result);
    });
}

export function ScanPeers(): $CancellablePromise<void> {
    return $Call.ByID(778632989);
}

export function SendFile(deviceID: string, path: string): $CancellablePromise<chat$0.Message> {
    return $Call.ByID(3741376625, deviceID, path).then(($result: any) => {
        return $$createType9($result);
    });
}

export function SendFriendRequest(deviceID: string, message: string): $CancellablePromise<chat$0.FriendRequest> {
    return $Call.ByID(3287173788, deviceID, message).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SendImage(deviceID: string, dataURL: string): $CancellablePromise<chat$0.Message> {
    return $Call.ByID(3554798020, deviceID, dataURL).then(($result: any) => {
        return $$createType9($result);
    });
}

export function SendMessage(deviceID: string, content: string): $CancellablePromise<chat$0.Message> {
    return $Call.ByID(2899218398, deviceID, content).then(($result: any) => {
        return $$createType9($result);
    });
}

export function SetAutoSave(value: boolean): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(1430800165, value).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetAvatar(sourcePath: string): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(4034925466, sourcePath).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetDiscoverable(value: boolean): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(1466420968, value).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetFileSavePath(path: string): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(2225634807, path).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetLaunchAtStartup(value: boolean): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(2357719998, value).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetPeerRemark(deviceID: string, remark: string): $CancellablePromise<void> {
    return $Call.ByID(564551595, deviceID, remark);
}

export function SetTheme(theme: string): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(3559697452, theme).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(4196218095);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3900343349);
}

export function UpdateProfile(profile: chat$0.Profile): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(1072926097, profile).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = chat$0.Attachment.createFrom;
const $$createType1 = chat$0.DeviceInfo.createFrom;
const $$createType2 = chat$0.Profile.createFrom;
const $$createType3 = chat$0.Conversation.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = chat$0.FriendRequest.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = chat$0.Peer.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = chat$0.Message.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = chat$0.AttachmentMigrationResult.createFrom;
const $$createType12 = chat$0.NetworkStatus.createFrom;
const $$createType13 = chat$0.DiagnosticResult.createFrom;
