// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BaseSysSetting is the key/value data object for base_sys_setting.
type BaseSysSetting struct {
	g.Meta     `orm:"table:base_sys_setting, do:true"`
	Id         any         `json:"id"`
	CreateTime *gtime.Time `json:"createTime"`
	UpdateTime *gtime.Time `json:"updateTime"`
	DeletedAt  *gtime.Time `json:"deletedAt"`
	Key        any         `json:"key"`
	Value      any         `json:"value"`
}
