// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

type BaseSysSettingDao struct {
	table    string
	group    string
	columns  BaseSysSettingColumns
	handlers []gdb.ModelHandler
}

type BaseSysSettingColumns struct {
	Id         string
	CreateTime string
	UpdateTime string
	DeletedAt  string
	Key        string
	Value      string
}

var baseSysSettingColumns = BaseSysSettingColumns{
	Id:         "id",
	CreateTime: "createTime",
	UpdateTime: "updateTime",
	DeletedAt:  "deleted_at",
	Key:        "key",
	Value:      "value",
}

func NewBaseSysSettingDao(handlers ...gdb.ModelHandler) *BaseSysSettingDao {
	return &BaseSysSettingDao{
		group:    "default",
		table:    "base_sys_setting",
		columns:  baseSysSettingColumns,
		handlers: handlers,
	}
}

func (dao *BaseSysSettingDao) DB() gdb.DB                     { return g.DB(dao.group) }
func (dao *BaseSysSettingDao) Table() string                  { return dao.table }
func (dao *BaseSysSettingDao) Columns() BaseSysSettingColumns { return dao.columns }
func (dao *BaseSysSettingDao) Group() string                  { return dao.group }

func (dao *BaseSysSettingDao) Ctx(ctx context.Context) *gdb.Model {
	model := dao.DB().Model(dao.table)
	for _, handler := range dao.handlers {
		model = handler(model)
	}
	return model.Safe().Ctx(ctx)
}

func (dao *BaseSysSettingDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) error {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
