// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as chat$0 from "../chat/models.js";

export function AcceptAttachment(attachmentID: string): $CancellablePromise<chat$0.Attachment> {
    return $Call.ByID(4271119745, attachmentID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AcceptFriendRequest(requestID: string): $CancellablePromise<void> {
    return $Call.ByID(1185344757, requestID);
}

export function ClearApplicationData(): $CancellablePromise<void> {
    return $Call.ByID(524311113);
}

export function EnsureConversation(deviceID: string): $CancellablePromise<string> {
    return $Call.ByID(2831782417, deviceID);
}

export function GetDeviceInfo(): $CancellablePromise<chat$0.DeviceInfo> {
    return $Call.ByID(788172634).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetProfile(): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(3866860525).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListConversations(): $CancellablePromise<chat$0.Conversation[]> {
    return $Call.ByID(4218032224).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ListFriendRequests(): $CancellablePromise<chat$0.FriendRequest[]> {
    return $Call.ByID(410358690).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListFriends(): $CancellablePromise<chat$0.Peer[]> {
    return $Call.ByID(1975149917).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ListMessages(conversationID: string): $CancellablePromise<chat$0.Message[]> {
    return $Call.ByID(348580048, conversationID).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ListPeers(): $CancellablePromise<chat$0.Peer[]> {
    return $Call.ByID(1268832881).then(($result: any) => {
        return $$createType8($result);
    });
}

export function NetworkStatus(): $CancellablePromise<chat$0.NetworkStatus> {
    return $Call.ByID(2032026300).then(($result: any) => {
        return $$createType11($result);
    });
}

export function PickDirectory(): $CancellablePromise<string> {
    return $Call.ByID(51053304);
}

export function PickFile(): $CancellablePromise<string> {
    return $Call.ByID(534260371);
}

export function RejectAttachment(attachmentID: string): $CancellablePromise<void> {
    return $Call.ByID(1595010322, attachmentID);
}

export function RejectFriendRequest(requestID: string): $CancellablePromise<void> {
    return $Call.ByID(77182996, requestID);
}

export function ResetAvatar(): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(3017524946).then(($result: any) => {
        return $$createType2($result);
    });
}

export function RunNetworkDiagnostic(): $CancellablePromise<chat$0.DiagnosticResult> {
    return $Call.ByID(3973181866).then(($result: any) => {
        return $$createType12($result);
    });
}

export function ScanPeers(): $CancellablePromise<void> {
    return $Call.ByID(675702358);
}

export function SendFile(deviceID: string, path: string): $CancellablePromise<chat$0.Message> {
    return $Call.ByID(3992859524, deviceID, path).then(($result: any) => {
        return $$createType9($result);
    });
}

export function SendFriendRequest(deviceID: string, message: string): $CancellablePromise<chat$0.FriendRequest> {
    return $Call.ByID(273264067, deviceID, message).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SendMessage(deviceID: string, content: string): $CancellablePromise<chat$0.Message> {
    return $Call.ByID(255947113, deviceID, content).then(($result: any) => {
        return $$createType9($result);
    });
}

export function SetAutoSave(value: boolean): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(104311086, value).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetAvatar(sourcePath: string): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(2058178365, sourcePath).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetDiscoverable(value: boolean): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(31161087, value).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetFileSavePath(path: string): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(14523016, path).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetLaunchAtStartup(value: boolean): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(2952417935, value).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetPeerRemark(deviceID: string, remark: string): $CancellablePromise<void> {
    return $Call.ByID(2217507332, deviceID, remark);
}

export function SetTheme(theme: string): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(3770817345, theme).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(2618950928);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3502916372);
}

export function UpdateProfile(profile: chat$0.Profile): $CancellablePromise<chat$0.Profile> {
    return $Call.ByID(2217326982, profile).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = chat$0.Attachment.createFrom;
const $$createType1 = chat$0.DeviceInfo.createFrom;
const $$createType2 = chat$0.Profile.createFrom;
const $$createType3 = chat$0.Conversation.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = chat$0.FriendRequest.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = chat$0.Peer.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = chat$0.Message.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = chat$0.NetworkStatus.createFrom;
const $$createType12 = chat$0.DiagnosticResult.createFrom;
