// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Attachment {
    "attachmentId": string;
    "messageId": string;
    "fileName": string;
    "mimeType": string;
    "fileSize": number;
    "sha256": string;
    "localPath": string;
    "status": string;

    /** Creates a new Attachment instance. */
    constructor($$source: Partial<Attachment> = {}) {
        if (!("attachmentId" in $$source)) {
            this["attachmentId"] = "";
        }
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("mimeType" in $$source)) {
            this["mimeType"] = "";
        }
        if (!("fileSize" in $$source)) {
            this["fileSize"] = 0;
        }
        if (!("sha256" in $$source)) {
            this["sha256"] = "";
        }
        if (!("localPath" in $$source)) {
            this["localPath"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Attachment instance from a string or object.
     */
    static createFrom($$source: any = {}): Attachment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Attachment($$parsedSource as Partial<Attachment>);
    }
}

export class AttachmentMigrationResult {
    "sourceRoot": string;
    "targetRoot": string;
    "total": number;
    "migrated": number;
    "skipped": number;
    "failed": number;
    "unclassified": number;
    "completed": boolean;
    "errorMessage"?: string;

    /** Creates a new AttachmentMigrationResult instance. */
    constructor($$source: Partial<AttachmentMigrationResult> = {}) {
        if (!("sourceRoot" in $$source)) {
            this["sourceRoot"] = "";
        }
        if (!("targetRoot" in $$source)) {
            this["targetRoot"] = "";
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("migrated" in $$source)) {
            this["migrated"] = 0;
        }
        if (!("skipped" in $$source)) {
            this["skipped"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }
        if (!("unclassified" in $$source)) {
            this["unclassified"] = 0;
        }
        if (!("completed" in $$source)) {
            this["completed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AttachmentMigrationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): AttachmentMigrationResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AttachmentMigrationResult($$parsedSource as Partial<AttachmentMigrationResult>);
    }
}

export class Conversation {
    "conversationId": string;
    "peerDeviceId": string;
    "lastMessage": string;
    "lastMessageAt": string;
    "unreadCount": number;
    "pinned": boolean;

    /** Creates a new Conversation instance. */
    constructor($$source: Partial<Conversation> = {}) {
        if (!("conversationId" in $$source)) {
            this["conversationId"] = "";
        }
        if (!("peerDeviceId" in $$source)) {
            this["peerDeviceId"] = "";
        }
        if (!("lastMessage" in $$source)) {
            this["lastMessage"] = "";
        }
        if (!("lastMessageAt" in $$source)) {
            this["lastMessageAt"] = "";
        }
        if (!("unreadCount" in $$source)) {
            this["unreadCount"] = 0;
        }
        if (!("pinned" in $$source)) {
            this["pinned"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Conversation instance from a string or object.
     */
    static createFrom($$source: any = {}): Conversation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Conversation($$parsedSource as Partial<Conversation>);
    }
}

export class DeviceInfo {
    "platform": string;
    "osVersion": string;
    "deviceId": string;
    "publicKeyPem": string;
    "certificateFingerprint": string;
    "ip": string;
    "port": number;

    /** Creates a new DeviceInfo instance. */
    constructor($$source: Partial<DeviceInfo> = {}) {
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("osVersion" in $$source)) {
            this["osVersion"] = "";
        }
        if (!("deviceId" in $$source)) {
            this["deviceId"] = "";
        }
        if (!("publicKeyPem" in $$source)) {
            this["publicKeyPem"] = "";
        }
        if (!("certificateFingerprint" in $$source)) {
            this["certificateFingerprint"] = "";
        }
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceInfo($$parsedSource as Partial<DeviceInfo>);
    }
}

export class DiagnosticItem {
    "name": string;
    "status": string;
    "detail": string;
    "advice": string;

    /** Creates a new DiagnosticItem instance. */
    constructor($$source: Partial<DiagnosticItem> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }
        if (!("advice" in $$source)) {
            this["advice"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiagnosticItem instance from a string or object.
     */
    static createFrom($$source: any = {}): DiagnosticItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiagnosticItem($$parsedSource as Partial<DiagnosticItem>);
    }
}

export class DiagnosticResult {
    "status": string;
    "items": DiagnosticItem[];
    "createdAt": string;

    /** Creates a new DiagnosticResult instance. */
    constructor($$source: Partial<DiagnosticResult> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiagnosticResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DiagnosticResult {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField1_0($$parsedSource["items"]);
        }
        return new DiagnosticResult($$parsedSource as Partial<DiagnosticResult>);
    }
}

export class FriendRequest {
    "requestId": string;
    "deviceId": string;
    "nickname": string;
    "message": string;
    "status": string;
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new FriendRequest instance. */
    constructor($$source: Partial<FriendRequest> = {}) {
        if (!("requestId" in $$source)) {
            this["requestId"] = "";
        }
        if (!("deviceId" in $$source)) {
            this["deviceId"] = "";
        }
        if (!("nickname" in $$source)) {
            this["nickname"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FriendRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): FriendRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FriendRequest($$parsedSource as Partial<FriendRequest>);
    }
}

export class Message {
    "messageId": string;
    "conversationId": string;
    "senderDeviceId": string;
    "kind": string;
    "content": string;
    "status": string;
    "createdAt": string;
    "attachmentId"?: string;
    "attachmentName"?: string;
    "attachmentSize"?: number;
    "attachmentMime"?: string;
    "attachmentStatus"?: string;
    "attachmentPath"?: string;

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }
        if (!("conversationId" in $$source)) {
            this["conversationId"] = "";
        }
        if (!("senderDeviceId" in $$source)) {
            this["senderDeviceId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Message($$parsedSource as Partial<Message>);
    }
}

export class NetworkStatus {
    "status": string;
    "interfaces": string[];
    "localIps": string[];
    "discoveryPort": number;
    "chatPort": number;
    "peerCount": number;
    "onlineCount": number;
    "lastScanAt": string;
    "lastError": string;

    /** Creates a new NetworkStatus instance. */
    constructor($$source: Partial<NetworkStatus> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("interfaces" in $$source)) {
            this["interfaces"] = [];
        }
        if (!("localIps" in $$source)) {
            this["localIps"] = [];
        }
        if (!("discoveryPort" in $$source)) {
            this["discoveryPort"] = 0;
        }
        if (!("chatPort" in $$source)) {
            this["chatPort"] = 0;
        }
        if (!("peerCount" in $$source)) {
            this["peerCount"] = 0;
        }
        if (!("onlineCount" in $$source)) {
            this["onlineCount"] = 0;
        }
        if (!("lastScanAt" in $$source)) {
            this["lastScanAt"] = "";
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): NetworkStatus {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("interfaces" in $$parsedSource) {
            $$parsedSource["interfaces"] = $$createField1_0($$parsedSource["interfaces"]);
        }
        if ("localIps" in $$parsedSource) {
            $$parsedSource["localIps"] = $$createField2_0($$parsedSource["localIps"]);
        }
        return new NetworkStatus($$parsedSource as Partial<NetworkStatus>);
    }
}

export class Peer {
    "deviceId": string;
    "nickname": string;
    "avatarPath": string;
    "avatarData"?: string;
    "avatarHash"?: string;
    "avatarVersion"?: number;
    "platform": string;
    "osVersion": string;
    "ip": string;
    "port": number;
    "publicKeyPem": string;
    "certificateFingerprint": string;
    "relation": string;
    "remark": string;
    "online": boolean;
    "lastSeen": string;
    "updatedAt": string;

    /** Creates a new Peer instance. */
    constructor($$source: Partial<Peer> = {}) {
        if (!("deviceId" in $$source)) {
            this["deviceId"] = "";
        }
        if (!("nickname" in $$source)) {
            this["nickname"] = "";
        }
        if (!("avatarPath" in $$source)) {
            this["avatarPath"] = "";
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("osVersion" in $$source)) {
            this["osVersion"] = "";
        }
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("publicKeyPem" in $$source)) {
            this["publicKeyPem"] = "";
        }
        if (!("certificateFingerprint" in $$source)) {
            this["certificateFingerprint"] = "";
        }
        if (!("relation" in $$source)) {
            this["relation"] = "";
        }
        if (!("remark" in $$source)) {
            this["remark"] = "";
        }
        if (!("online" in $$source)) {
            this["online"] = false;
        }
        if (!("lastSeen" in $$source)) {
            this["lastSeen"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Peer instance from a string or object.
     */
    static createFrom($$source: any = {}): Peer {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Peer($$parsedSource as Partial<Peer>);
    }
}

export class Profile {
    "nickname": string;
    "avatarPath": string;
    "avatarData"?: string;
    "avatarHash"?: string;
    "avatarVersion"?: number;
    "discoverable": boolean;
    "autoSave": boolean;
    "fileSavePath": string;
    "theme": string;
    "launchAtStartup": boolean;

    /** Creates a new Profile instance. */
    constructor($$source: Partial<Profile> = {}) {
        if (!("nickname" in $$source)) {
            this["nickname"] = "";
        }
        if (!("avatarPath" in $$source)) {
            this["avatarPath"] = "";
        }
        if (!("discoverable" in $$source)) {
            this["discoverable"] = false;
        }
        if (!("autoSave" in $$source)) {
            this["autoSave"] = false;
        }
        if (!("fileSavePath" in $$source)) {
            this["fileSavePath"] = "";
        }
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("launchAtStartup" in $$source)) {
            this["launchAtStartup"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Profile instance from a string or object.
     */
    static createFrom($$source: any = {}): Profile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Profile($$parsedSource as Partial<Profile>);
    }
}

// Private type creation functions
const $$createType0 = DiagnosticItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
