// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import "github.com/gogf/gf/v2/os/gtime"

// BaseSysSetting is the key/value entity for base_sys_setting.
type BaseSysSetting struct {
	Id         string      `json:"id" orm:"id"`
	CreateTime *gtime.Time `json:"createTime" orm:"createTime"`
	UpdateTime *gtime.Time `json:"updateTime" orm:"updateTime"`
	DeletedAt  *gtime.Time `json:"deletedAt" orm:"deleted_at"`
	Key        string      `json:"key" orm:"key"`
	Value      string      `json:"value" orm:"value"`
}
